paramSets:
  -
    name: 128s
    pkSize: 32
    skSize: 64
    sigSize: 7856
  -
    name: 128f
    pkSize: 32
    skSize: 64
    sigSize: 17088
  -  
    name: 192s
    pkSize: 48
    skSize: 96
    sigSize: 16224
  -  
    name: 192f
    pkSize: 48
    skSize: 96
    sigSize: 35664
  -  
    name: 256s
    pkSize: 64
    skSize: 128
    sigSize: 29792
  -  
    name: 256f
    pkSize: 64
    skSize: 128
    sigSize: 49856

hashAlgs:
  -
    name: sha2
  -
    name: shake

prehashHashAlgs:
  -
    name: sha2_224
  -
    name: sha2_256
  -
    name: sha2_384
  -
    name: sha2_512
  -
    name: sha2_512_224
  -
    name: sha2_512_256
  -
    name: sha3_224
  -
    name: sha3_256
  -
    name: sha3_384
  -
    name: sha3_512
  -
    name: shake_128
  -
    name: shake_256